{
    "on": { "push": { "branches": ["main"] }, "pull_request": {} },
    "name": "Clippy",
    "permissions": { "security-events": "write" },
    "jobs":
        {
            "enforce-clippy":
                {
                    "runs-on": "ubuntu-latest",
                    "steps":
                        [
                            {
                                "name": "Checkout",
                                "uses": "actions/checkout@v4",
                            },
                            {
                                "name": "Install",
                                "uses": "./.github/workflows/install.yml@main",
                            },
                            {
                                "name": "Generate SARIF",
                                "run":
                                    "cargo clippy --all-features --message-format=json |
                                    clippy-sarif | tee results.sarif | sarif-fmt",
                            },
                            {
                                "name": "Upload SARIF file",
                                "uses": "github/codeql-action/upload-sarif@v2",
                                "with": { "sarif_file": "results.sarif" },
                            },
                        ],
                },
        },
}
